baseURL: https://polarbear.army/
title: polarbear.army
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true
enableInlineShortcodes: true
timeZone: "UTC"
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: nord

minify:
  disableXML: true
  minifyOutput: true

params:
  homeInfoParams:
    Title: Hi
    Content: Can be Info, links, about...
  assets:
    favicon: "/favicon.svg"
    favicon192x192:  "/favicon-192x192.png"

  socialIcons: # optional
    - name: "<platform>"
      url: "https://example.com"
    - name: "<platform 2>"
      url: "https://example.com"

taxonomies:
  category: categories
  tag: tags

menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON
